services:
  - type: worker
    name: platorelay-bypass-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: BACON_API_KEY
        sync: false
    autoDeploy: true